# Loads default set of integrations. Do not remove.
default_config:

# Support live video streaming
ffmpeg:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Enable packages
homeassistant:
  packages: !include_dir_named packages/

# Expose Home Assistant to the tailscale network
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

# Increase history retention to 14 days for predbat to have enough data for accurate predictions
recorder:
  purge_keep_days: 14
