FROM registry.redhat.io/rhel10/rhel-bootc:10.1

# Signal that this image is intended to be usable with bootc
LABEL containers.bootc 1

#install software
#RUN dnf -y install tmux mkpasswd

#configure bootc-user
#RUN pass=$(mkpasswd --method=SHA-512 --rounds=4096 redhat) && useradd -m -G wheel bootc-user -p $pass

#setup sudo to not require password
RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo

# Final lint step to prevent easy-to-catch issues at build time
RUN bootc container lint
