automation:
  - id: "solcast_update_forecasts"
    alias: Solcast update
    description: "Additional forecast updates at night (integration API limit needs to be adjusted)"
    trigger:
      - platform: time
        at:
          - "2:00:00"
    condition:
      - condition: time
        after: "01:00:00"
        before: "03:00:00"
    action:
      - delay:
          seconds: "{{ range(30, 360)|random|int }}"
      - service: solcast_solar.force_update_forecasts
        data: {}
    mode: single
