sensor:
  # Riemann sum integration sensors (W -> kWh)
  - platform: integration
    source: sensor.custom_goodwe_energy_import
    name: "Custom Goodwe Energy Import Sum"
    unique_id: custom_goodwe_energy_import_sum
    unit_prefix: k
    round: 2
    method: left

  - platform: integration
    source: sensor.custom_goodwe_energy_export
    name: "Custom Goodwe Energy Export Sum"
    unique_id: custom_goodwe_energy_export_sum
    unit_prefix: k
    round: 2
    method: left

  - platform: integration
    source: sensor.custom_goodwe_energy_battery_charge
    name: "Custom Goodwe Energy Battery Charge Sum"
    unique_id: custom_goodwe_energy_battery_charge_sum
    unit_prefix: k
    round: 2
    method: left

  - platform: integration
    source: sensor.custom_goodwe_energy_battery_discharge
    name: "Custom Goodwe Energy Battery Discharge Sum"
    unique_id: custom_goodwe_energy_battery_discharge_sum
    unit_prefix: k
    round: 2
    method: left

  - platform: integration
    source: sensor.pv_power
    name: "Custom Goodwe PV Power Sum"
    unique_id: custom_goodwe_pv_power_sum
    unit_prefix: k
    round: 2
    method: left

  - platform: integration
    source: sensor.custom_goodwe_house_consumption
    name: "Custom Goodwe House Consumption Sum"
    unique_id: custom_goodwe_house_consumption_sum
    unit_prefix: k
    round: 2
    method: left
