---
name: Check Nix formatting

on:
  pull_request:
    paths:
      - "**/*.nix"
      - "flake.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-formatting:
    name: Check Nix file formatting
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0

      - name: Check formatting
        run: |
          echo "Checking Nix file formatting with nixfmt-rfc-style..."
          nix fmt -- --check .
