#ENC[AES256_GCM,data:CXDOmCuD+D5mGo805llyaA==,iv:d22x2MMb24ax4jwngWaDRelNFqzabhb4r1Sd4DGGn3M=,tag:ByNTZLRfxTropG0aHX12yw==,type:comment]
api_encryption_key: ENC[AES256_GCM,data:Hio+0EdJiKrS0bXuuSbESvHIhDHtKsYDGAH3p5HjNTe9PBFmZ8xi4JNhLX0=,iv:BPpufJHuswXd0P6x90LBWBkMGqDCNCKrkrI4dTcY/mQ=,tag:aFqtDAO1qXdAZZ2iIKBKTA==,type:str]
ota_password: ENC[AES256_GCM,data:9fIW6WBV1UFa/0TgXJuJk5nR9lRB1VoN0JJ+cuEQYDc=,iv:VTiAnbl0ghgQ8Xz0e4Q+EWaeI5m5MUoVs8JmBxshGcE=,tag:/W8IlbG2D/6+wkAvM+kb5Q==,type:str]
#ENC[AES256_GCM,data:V9VeEs6U3tB1ioJ2FO0WMg==,iv:okvHI8EBiop6/czuRKL4sGFP3SCzJybjjo736wjumcw=,tag:2PfgMiEi3DkRA9z6YEBapw==,type:comment]
blind_id_cozinha_porta: ENC[AES256_GCM,data:f7Ov4/lAUQGUJw==,iv:WZFShbr4EzColxKlJdbh8HIFj7SqeqRENYO17v6XBgg=,tag:rN0s1owc1n2O6qQK/qo6dA==,type:str]
blind_id_cozinha_vidro_fixo: ENC[AES256_GCM,data:NmRhzhY1eEGTtA==,iv:sPQZ0DFlTPdE4AYzPw+D0bMPi35k50g76GktKzR43ig=,tag:YJEVoMxnlBVqjBLAktXN1w==,type:str]
blind_id_quarto_lucas: ENC[AES256_GCM,data:OQNPrmoyVjRO2g==,iv:oVp+8DUrxpaC+cty/MMlL2aQwM3oDjAeFmv8xgRNgV4=,tag:aLIe3a8d+bGmL/j/39e4gA==,type:str]
blind_id_quarto_sofia: ENC[AES256_GCM,data:gt/KP4etcwrPiA==,iv:dyhfVBQw4VCcq/6jk1SWXZ4gxCp4Uw0HAfLXgGvBye8=,tag:MRy6vZKIYhdT0dsAh26v7g==,type:str]
blind_id_sala_sinuca_direita: ENC[AES256_GCM,data:d5WU6CcHRCGn/A==,iv:9YHIvpfZbjOLknVyPYS9FzZjpj//LM0NSs035MqB+Ts=,tag:2YTdbWkP9yPiJ/OyGLIP2Q==,type:str]
blind_id_sala_sinuca_esquerda: ENC[AES256_GCM,data:c74dNzRseBM9vA==,iv:Ho4sgeefQ5NrgNiaJnNECLGXUexTbru4RWIcTPXxfnI=,tag:jMiDti2ccQtjOB5g0Jbz4w==,type:str]
sops:
    age:
        - recipient: age140f400lm4tcmhcxnl67gt4z6edrzafelh5xtuyap9fusj8lhqq0qg0pw2x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb2ZsQWd4YW9DcFhxbER5
            K0RFN0VwUm5GcEhldWJ2MmlHSVcxOVorMXk0Cm03SDM0c2JaaWxpZ05uNGhUV2NP
            MTc0MjczdHcyNkl4QWQvTFgyYU1LbVUKLS0tIFFnTHU0N2J6aysxcUl2Rk12U1I1
            bDRSMHc1UzJMbFNmaHVQc2drTm0vczQKaB6Eb/3x79jU58RmVhwMwuJtEYmdLU3T
            aWjSpZHMgpVLV93snRDTFptqSMxCRQ9C2QOD9rMv2oUJ/h2qKhcwIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18n5qk8e4rrz42rjkk6ed6z3qugzq3jdm8kgavwwfaq6tgq6mm50qsq2tux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV1FKS21FY05icWxZeUhy
            RTQwS2p6MHphZzdFb3U5eklMOHJNZFZsYVhFCmdoQXNqZzNVUVdMa1BVWkNickIx
            Qml2QStZUFZCNlZaUjFLYWxqM1Z5Q0kKLS0tIE1UYkhrR1VDcGVrdEUxOGZrU0d5
            ek03dXkvblh0d0pDV1lRdWw2c0hKeFUKw1z8THWw7rVc0o7irUet8l1fsnp9gIH8
            qmBg1P5/mYhSLAW7zlKkEVWI4YL8uGrGg+kTvSriDziOI9RlnMSk5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T01:10:12Z"
    mac: ENC[AES256_GCM,data:UmQWehLybebM/OHsX10K0EFeemDyViDCz1nzsfTp8r7krcDYl3+hJObWsAQELkypr1oZZeBpSR6ni8vsJ06Z/OYdW8SwLj06qTHxZLNc/Re+qzIFX2q2LL0+eE42OBKDdMsfpIfapd1cVa3LZltxV+BHbnXuzG3gsEQJtgwDtzA=,iv:KEj9TJIHpic90a/DH16/pnd1WXE5qZy7i9QGP2olgpE=,tag:6ytfZyJkSDGzmRuoO9tMVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
