#ENC[AES256_GCM,data:CXDOmCuD+D5mGo805llyaA==,iv:d22x2MMb24ax4jwngWaDRelNFqzabhb4r1Sd4DGGn3M=,tag:ByNTZLRfxTropG0aHX12yw==,type:comment]
api_encryption_key: ENC[AES256_GCM,data:Hio+0EdJiKrS0bXuuSbESvHIhDHtKsYDGAH3p5HjNTe9PBFmZ8xi4JNhLX0=,iv:BPpufJHuswXd0P6x90LBWBkMGqDCNCKrkrI4dTcY/mQ=,tag:aFqtDAO1qXdAZZ2iIKBKTA==,type:str]
ota_password: ENC[AES256_GCM,data:9fIW6WBV1UFa/0TgXJuJk5nR9lRB1VoN0JJ+cuEQYDc=,iv:VTiAnbl0ghgQ8Xz0e4Q+EWaeI5m5MUoVs8JmBxshGcE=,tag:/W8IlbG2D/6+wkAvM+kb5Q==,type:str]
sops:
    age:
        - recipient: age140f400lm4tcmhcxnl67gt4z6edrzafelh5xtuyap9fusj8lhqq0qg0pw2x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb2ZsQWd4YW9DcFhxbER5
            K0RFN0VwUm5GcEhldWJ2MmlHSVcxOVorMXk0Cm03SDM0c2JaaWxpZ05uNGhUV2NP
            MTc0MjczdHcyNkl4QWQvTFgyYU1LbVUKLS0tIFFnTHU0N2J6aysxcUl2Rk12U1I1
            bDRSMHc1UzJMbFNmaHVQc2drTm0vczQKaB6Eb/3x79jU58RmVhwMwuJtEYmdLU3T
            aWjSpZHMgpVLV93snRDTFptqSMxCRQ9C2QOD9rMv2oUJ/h2qKhcwIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18n5qk8e4rrz42rjkk6ed6z3qugzq3jdm8kgavwwfaq6tgq6mm50qsq2tux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV1FKS21FY05icWxZeUhy
            RTQwS2p6MHphZzdFb3U5eklMOHJNZFZsYVhFCmdoQXNqZzNVUVdMa1BVWkNickIx
            Qml2QStZUFZCNlZaUjFLYWxqM1Z5Q0kKLS0tIE1UYkhrR1VDcGVrdEUxOGZrU0d5
            ek03dXkvblh0d0pDV1lRdWw2c0hKeFUKw1z8THWw7rVc0o7irUet8l1fsnp9gIH8
            qmBg1P5/mYhSLAW7zlKkEVWI4YL8uGrGg+kTvSriDziOI9RlnMSk5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T20:43:07Z"
    mac: ENC[AES256_GCM,data:2/fcC+oRiSyWo+Vw1IksL09YOVTRaB/7dSO7K29RtNSAC15iAS/CBMJZH+bZzK6zdCpi6MmgeuuB836M+x0pWkniL0gXPuN5pG7z+fe8QDc2jda8g1VvSsBCk8ks1g/PSl6ScNmgG+gob+CQc55M3VNQeBj326TmHmblE/nbGAw=,iv:7w595/dCjBdtDVQFK5qpJfLgaOi8grPOlsqxY42riag=,tag:/Djtz32wQOcfDpczVfgSEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
